version: "2"
services:
  tkhdb:
    image: mongo:3.4.14
    expose:
      - "27017"
    volumes:
      - /data/db:/data/db
    restart: always

  tkh-api:
    image: kenth/tkh-api:latest
    depends_on:
      - tkhdb
    expose:
      - "8000"
    ports:
      - "8000:8080"
    restart: always

  tkh-web:
    image: kenth/tkh-web:latest
    depends_on:
      - tkh-api
    expose:
      - "9000"
    ports:
      - "9000:8080"
    restart: always
