version: "2"

services:
  traefik:
    image: traefik:1.7.2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tkh-build/traefik.toml:/traefik.toml
      - /tkh-build/acme.json:/acme.json
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:monitor.thomaskenthurd.com"
      - "traefik.basic.port=8080"
    container_name: traefik

networks:
  web:
    external: true
  internal:
    external: false
