debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["[REPLACE THIS ON SERVER]"]

[retry]

[api]
entrypoint="dashboard"


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "thomaskenthurd.com"
watch = true
exposedByDefault = false
network = "web"

[acme]
email = "kenth3@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

  
#[[acme.domains]]
#  main = "thomaskenthurd.com"
#  sans = ["thomaskenthurd.com", "www.thomaskenthurd.com", "monitor.thomaskenthurd.com", "api.thomaskenthurd.com", "web.thomaskenthurd.com"]

